# Generated by Django 5.1.2 on 2024-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('description', models.TextField(verbose_name='Описание сотрудника  ')),
                ('logo', models.ImageField(upload_to='logo_image/')),
            ],
        ),
    ]
